import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/recipe.dart';
import '../models/ingrediente_tabla.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

Future<Uint8List> generateRecipePdf(Recipe receta, {bool isEnglish = false, required String userName}) async {
  final pdf = pw.Document();
  final logoBytes = await rootBundle.load('assets/icon/icon.png');
  final logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());

  final fontColor = PdfColors.black;
  final backgroundColor = PdfColors.white;
  final primaryColor = PdfColor.fromInt(0xFF2B4C8C); 
  final accentColor = PdfColor.fromInt(0xFF4C75FA); 

  final Map<String, String> translations = {
    'Yield': isEnglish ? 'Yield' : 'Rendimiento',
    'Ingredients': isEnglish ? 'Ingredients' : 'Ingredientes',
    'Ingredient': isEnglish ? 'Ingredient' : 'Ingrediente',
    'Quantity': isEnglish ? 'Quantity' : 'Cantidad',
    'Unit': isEnglish ? 'Unit' : 'Unidad',
    'Steps': isEnglish ? 'Steps' : 'Pasos',
    'Generated by': isEnglish ? 'Generated by' : 'Generado por',
  };

  pw.Widget createHeader() {
    return pw.Container(
      color: backgroundColor,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Header(
            level: 0,
            child: pw.Text(
              receta.title,
              style: pw.TextStyle(
                color: primaryColor,
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 15),
          pw.Text(
            receta.description ?? '',
            style: pw.TextStyle(
              fontSize: 16,
              color: fontColor,
            ),
          ),
          pw.SizedBox(height: 15),
          pw.Text(
            '${translations['Yield']}: ${receta.servingSize}',
            style: pw.TextStyle(
              fontSize: 14,
              color: fontColor,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget createIngredientsTable() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          translations['Ingredients']!,
          style: pw.TextStyle(
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
            color: primaryColor,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey400),
          children: [
            pw.TableRow(
              decoration: pw.BoxDecoration(color: PdfColors.grey100),
              children: [
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8.0),
                  child: pw.Text(
                    translations['Ingredient']!,
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                    textAlign: pw.TextAlign.center,
                  ),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8.0),
                  child: pw.Text(
                    translations['Quantity']!,
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                    textAlign: pw.TextAlign.center,
                  ),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8.0),
                  child: pw.Text(
                    translations['Unit']!,
                    style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold,
                      color: primaryColor,
                    ),
                    textAlign: pw.TextAlign.center,
                  ),
                ),
              ],
            ),
            ...List.generate(receta.ingredients.length, (index) {
              final ingredient = receta.ingredients[index];

              return pw.TableRow(
                children: [
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(8.0),
                    child: pw.Text(ingredient.name, textAlign: pw.TextAlign.left),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(8.0),
                    child: pw.Text(ingredient.quantity.toString(), textAlign: pw.TextAlign.center),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(8.0),
                    child: pw.Text(ingredient.unit, textAlign: pw.TextAlign.center),
                  ),
                ],
              );
            }),
          ],
        ),
      ],
    );
  }

  pw.Widget createStep(int index, String step) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 25,
            height: 25,
            decoration: pw.BoxDecoration(
              color: primaryColor,
              shape: pw.BoxShape.circle,
            ),
            alignment: pw.Alignment.center,
            child: pw.Text(
              '${index + 1}',
              style: pw.TextStyle(
                color: PdfColors.white,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(width: 10),
          pw.Expanded(
            child: pw.Text(
              step,
              style: pw.TextStyle(
                color: fontColor,
                height: 1.2,
              ),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget createFooter() {
    return pw.Container(
      child: pw.Column(
        children: [
          pw.Divider(),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Gauge your Recipe',
                style: pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.grey600,
                ),
              ),
              pw.Text(
                '${translations['Generated by']}: $userName',
                style: pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(20),
      header: (pw.Context context) => pw.Container(),
      footer: (pw.Context context) => createFooter(),
      build: (pw.Context context) => [
        createHeader(),
        pw.SizedBox(height: 15),
        createIngredientsTable(),
        pw.SizedBox(height: 15),
        if (receta.steps.isNotEmpty) ...[
          pw.Text(
            translations['Steps']!,
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: primaryColor,
            ),
          ),
          pw.SizedBox(height: 4),
          for (int i = 0; i < receta.steps.length; i++) createStep(i, receta.steps[i]),
        ],
      ],
    ),
  );

  return pdf.save();
}
